
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http: !include http.yaml


#emulated_hue:
#  host_ip: 10.0.2.250
#  listen_port: 80
#  expose_by_default: true
#  exposed_domains:
#    - light
#    - switch
